### ISSUE TITLE
org.datanucleus.store.rdbms.exceptions.NoTableManagedException

### ISSUE THREAD

**Issue by jnuyanfa** [bsautner/com.nimbits#195]
Hi:
  I import the project into my IntelliJ IDEA(2016.3.4), when I ran it with Tomcat (8.5), I got the **NoTableManagedException**. 
```java
2017-03-03 02:51:50 WARN  Query:106 - Query for candidates of com.nimbits.server.orm.PointEntity and subclasses resulted in no possible candidates
Persistent class "com.nimbits.server.orm.PointEntity" has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
org.datanucleus.store.rdbms.exceptions.NoTableManagedException: Persistent class "com.nimbits.server.orm.PointEntity" has no table in the database, but the operation requires it. Please check the specification of the MetaData for this class.
	at org.datanucleus.store.rdbms.RDBMSStoreManager.getDatastoreClass(RDBMSStoreManager.java:698)
	at org.datanucleus.store.rdbms.query.RDBMSQueryUtils.getStatementForCandidates(RDBMSQueryUtils.java:425)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileQueryFull(JDOQLQuery.java:896)
	at org.datanucleus.store.rdbms.query.JDOQLQuery.compileInternal(JDOQLQuery.java:344)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1816)
	at org.datanucleus.store.query.Query.executeWithArray(Query.java:1744)
	at org.datanucleus.api.jdo.JDOQuery.execute(JDOQuery.java:278)
	at com.nimbits.server.process.cron.SystemTaskExecutor.processIdlePoints(SystemTaskExecutor.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by bsautner** [comment]
Hi, this error is from the enhancer not running.  Running `datanucleus:enhance` with maven will fix this.   Setting up a dev environment for this project can be difficult and requires a knowledge of maven and spring - i hope this helps
